site_name: API Evertec Colombia
nav:
    - Introducción: index.md
    - Concepto importantes: Overview.md
    - Conectar con la API: 
        - Registro de aplicaciones: App_Register.md
        - Asegurar una clave API: Securing_AppKey.md
    - Identificación de aplicaciones: App_setup.md
    - Pasos para crear un JWT: JWT_build.md
    - Solicitar un token de autenticación: JWT_request.md
    - Generar un token de autenticación: Generate-Token.md
    - Enviar un token de autenticación: Send-Token.md
    - Transacciones:
        - Compra con token: payment-token.md
        - Consulta de recaudo en línea: collect-inquiry.md
        - Depósito con activación: Deposit.md
        - Generación de token de pagos (Generalidades): generate-payment-token-info.md
        - Generación de token de pagos: generate-payment-token.md        
        - Recaudo en línea: collect.md
        - Retiro o avance con token: withdrawal-token.md
    - Anulaciones:
        - Anulación de una transacción: refund.md
    - Reversos:
        - Reverso de una transacción: reverse.md
    - Consultas:
        - Consulta de productos de un afiliado: product-inquiry.md
theme: readthedocs
