site_name: API Evertec Colombia
nav:
    - Introducción: index.md
    - Concepto importantes: Overview.md
    - Conectar con la API: 
        - Registro de aplicaciones: App_Register.md
        - Asegurar una clave API: Securing_AppKey.md
    - Identificación de aplicaciones: App_setup.md
    - Pasos para crear un JWT: JWT_build.md
    - Solicitar un token de autenticación: JWT_request.md
    - Generar un token de autenticación: Generate-Token.md
    - Enviar un token de autenticación: Send-Token.md
    - Transacciones:
        - Compra con token: payment-token.md
        - Depósito con activación: Deposit.md
        - Generar token de compra: generate-payment-token.md
        - Recaudo en línea: collect.md
        - Retiro con token (Avance): withdrawal-token.md
    - Anulaciones:
        - Anulación de una transacción: refund.md
    - Reversos:
        - Reverso de anulación de compra con token: payment-token-refund-reverse.md
        - Reverso de anulación de depósito con activación: DepositRefundReverse.md
        - Reverso de anulación de recaudo en línea: collect-refund-reverse.md
        - Reverso de anulación de retiro con token (Avance): withdrawal-token-refund-reverse.md
        - Reverso de compra con token: payment-token-reverse.md
        - Reverso de depósito con activación: DepositReverse.md
        - Reverso de retiro con token (Avance): withdrawal-token-reverse.md
theme: readthedocs
